[project]
name = "chromadb_etl"
version = "0.1"
dependencies = [
   "PyPDF2",
   "retry",
   "langchain_community",
   "langchain",
   "langchain_openai",
   "unstructured",
   "chromadb"
]

[project.optional-dependencies]
dev = ["black", "flake8"]